
function suppliment(){
	var reviewStartTimeLabel = '询比评审时间<span></span>';
	if (packageInfo.encipherStatus == 1) {
		reviewStartTimeLabel = '开启时间';
	}
	var List="";
		List+='<tr>'
     		+'<td style="width:220px;" class="th_bg">'+(examType==0?'资格预审':'')+'公告开始时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="noticeStartDate"></div>'     			
     		+'</td >'
     		+'<td style="width:220px;" class="th_bg">'+(examType==0?'资格预审':'')+'公告截止时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="noticeEndDate"></div>'     			
     		+'</td >'
     	+'</tr>'
     	if(packageInfo.isSign==1){
     	List+='<tr>'
     		+'<td style="width:220px;" class="th_bg">报名开始时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="signStartDate"></div>'     			
     		+'</td >'
     		+'<td style="width:220px;" class="th_bg">原始报名开始时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="oldSignStartDate"></div>'     			
     		+'</td >'
     	+'</tr>'
     	List+='<tr>'
     		+'<td style="width:220px;" class="th_bg">报名截止时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="signEndDate"></div>'     			
     		+'</td >'
     		+'<td style="width:220px;" class="th_bg">原始报名截止时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="oldSignEndDate"></div>'     			
     		+'</td >'
     	+'</tr>'
     	}
		List+='<tr>'
     		+'<td style="width:220px;" class="th_bg">'+(examType==0?'资格预审':'')+'提出澄清截止时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="'+(examType==0?'examAskEndDate':'askEndDate')+'"></div>'     			
     		+'</td >'
     		+'<td style="width:220px;" class="th_bg">'+(examType==0?'原始资格预审':'原始')+'提出澄清截止时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="'+(examType==0?'oldExamAskEndDate':'oldAskEndDate')+'"></div>'     			
     		+'</td >'
     	+'</tr>' 
     	List+='<tr>'
     		+'<td style="width:220px;" class="th_bg">'+(examType==0?'资格预审':'')+'答复截止时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="'+(examType==0?'examAnswersEndDate':'answersEndDate')+'"></div>'     			
     		+'</td >'
     		+'<td style="width:220px;" class="th_bg">'+(examType==0?'原始资格预审':'原始')+'答复截止时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="'+(examType==0?'oldExamAnswersEndDate':'oldAnswersEndDate')+'"></div>'     			
     		+'</td >'
     	+'</tr>'
     	if(examType==1){
     	List+='<tr>'
     		+'<td style="width:220px;" class="th_bg">报价截止时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="offerEndDate"></div>'     			
     		+'</td >'
     		+'<td style="width:220px;" class="th_bg">原始报价截止时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="oldOfferEndDate"></div>'	
     		+'</td>'
     	+'</tr>'
     	List+='<tr>'
     		+'<td style="width:220px;" class="th_bg">' + reviewStartTimeLabel + '</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="checkEndDate"></div>'     			
     		+'</td >'
     		+'<td style="width:220px;" class="th_bg">原始' + reviewStartTimeLabel + '</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="oldCheckEndDate"></div>'	
     		+'</td>'
     	+'</tr>'
     	}
     	if(examType==0){
     	List+='<tr>'
     		+'<td style="width:220px;" class="th_bg">资格预审申请文件递交截止时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="submitExamFileEndDate"></div>'	
     		+'</td>'
     		+'<td style="width:220px;" class="th_bg">原始资格预审申请文件递交截止时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="oldSubmitExamFileEndDate"></div>'	
     		+'</td>'
     	+'</tr>'
     	List+='<tr>'
     		+'<td style="width:220px;" class="th_bg">资格预审时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="examCheckEndDate"></div>'	
     		+'</td>'
     		+'<td style="width:220px;" class="th_bg">原始资格预审时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="oldExamCheckEndDate"></div>'	
     		+'</td>'
     	+'</tr>'
     	}
	$("#nowOrOld").html(List)
}

function examSuppliment(){
	var reviewStartTimeLabel = '询比评审时间<span></span>';
	if (packageInfo.encipherStatus == 1) {
		reviewStartTimeLabel = '开启时间';
	}
	var List="";
	if(examType==1){
		List+='<tr>'
     		+'<td style="width:220px;" class="th_bg">接受邀请开始时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="noticeStartDate"></div>'     			
     		+'</td >'
     		+'<td style="width:220px;" class="th_bg">接受邀请截止时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="noticeEndDate"></div>'     			
     		+'</td >'
     	+'</tr>'
     	if(packageInfo.isSign==1){
	     	List+='<tr>'
	     		+'<td style="width:220px;" class="th_bg">报名开始时间</td>'
	     		+'<td style="text-align: left;">'
	     			+'<div id="signStartDate"></div>'     			
	     		+'</td >'
	     		+'<td style="width:220px;" class="th_bg">原始报名开始时间</td>'
	     		+'<td style="text-align: left;">'
	     			+'<div id="oldSignStartDate"></div>'     			
	     		+'</td >'
	     	+'</tr>'
	     	List+='<tr>'
	     		+'<td style="width:220px;" class="th_bg">报名截止时间</td>'
	     		+'<td style="text-align: left;">'
	     			+'<div id="signEndDate"></div>'     			
	     		+'</td >'
	     		+'<td style="width:220px;" class="th_bg">原始报名截止时间</td>'
	     		+'<td style="text-align: left;">'
	     			+'<div id="oldSignEndDate"></div>'     			
	     		+'</td >'
	     	+'</tr>'
	     	}
	}
		     	
		List+='<tr>'
     		+'<td style="width:220px;" class="th_bg">提出澄清截止时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="askEndDate"></div>'     			
     		+'</td >'
     		+'<td style="width:220px;" class="th_bg">原始提出澄清截止时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="oldAskEndDate"></div>'     			
     		+'</td >'
     	+'</tr>' 
     	List+='<tr>'
     		+'<td style="width:220px;" class="th_bg">答复截止时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="answersEndDate"></div>'     			
     		+'</td >'
     		+'<td style="width:220px;" class="th_bg">原始答复截止时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="oldAnswersEndDate"></div>'     			
     		+'</td >'
     	+'</tr>'
     	if(examType==0){
     		List+='<tr>'
     		+'<td style="width:220px;" class="th_bg">接受邀请截止时间</td>'
	     		+'<td style="text-align: left;">'
	     			+'<div id="acceptEndDate"></div>'     			
	     		+'</td >'
	     		+'<td style="width:220px;" class="th_bg">原始接受邀请截止时间</td>'
	     		+'<td style="text-align: left;">'
	     			+'<div id="oldAcceptEndDate"></div>'     			
	     		+'</td >'
	     	+'</tr>'
     	}
     	List+='<tr>'
     		+'<td style="width:220px;" class="th_bg">报价截止时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="offerEndDate"></div>'     			
     		+'</td >'
     		+'<td style="width:220px;" class="th_bg">原始报价截止时间</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="oldOfferEndDate"></div>'	
     		+'</td>'
     	+'</tr>'
     	List+='<tr>'
     		+'<td style="width:220px;" class="th_bg">' + reviewStartTimeLabel + '</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="checkEndDate"></div>'     			
     		+'</td >'
     		+'<td style="width:220px;" class="th_bg">原始' + reviewStartTimeLabel + '</td>'
     		+'<td style="text-align: left;">'
     			+'<div id="oldCheckEndDate"></div>'	
     		+'</td>'
     	+'</tr>'
	$("#nowOrOld").html(List)
}
