/* 后审标段部分 */
var postHtml = '';
function creatPostHtml(){
	postHtml += '<tr class="isOnline examType2">'
		postHtml += '<td class="th_bg">招标文件获取方式</td>'
		postHtml += '<td>'
			postHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" checked="checked" name="signUpType" id="" value="1" style="vertical-align: -2px;margin-right: 5px;" />线上获取'
			postHtml += '</label>'
		postHtml += '</td>'
		postHtml += '<td class="th_bg">投标文件递交方式</td>'
		postHtml += '<td>'
			postHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" checked="checked" name="deliverFileType" class="bidFileEdit" id="" value="1" style="vertical-align: -2px;margin-right: 5px;" />线上递交'
			postHtml += '</label>'
			postHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" name="deliverFileType" id="" value="2" class="bidFileEdit" style="vertical-align: -2px;margin-right: 5px;" />线下递交'
			postHtml += '</label>'
		postHtml += '</td>'
	postHtml += '</tr>'
	postHtml += '<tr class="isOnline examType2">'
		postHtml += '<td class="th_bg">开标方式</td>'
		postHtml += '<td>'
			postHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" checked="checked" name="bidOpenType" class="bidFileEdit" id="" value="1" style="vertical-align: -2px;margin-right: 5px;" />线上开标'
			postHtml += '</label>'
			postHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" name="bidOpenType" id="" value="2" class="bidFileEdit" style="vertical-align: -2px;margin-right: 5px;" />线下开标'
			postHtml += '</label>'
	  postHtml += '</td>'
		postHtml += '<td class="th_bg">评审方式</td>'
		postHtml += '<td>'
			postHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" checked="checked" name="bidCheckType"class="bidFileEdit" id="" value="1" style="vertical-align: -2px;margin-right: 5px;" />线上评审'
			postHtml += '</label>'
			postHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" name="bidCheckType"class="bidFileEdit" id="" value="2" style="vertical-align: -2px;margin-right: 5px;" />线下评审'
			postHtml += '</label>'
		postHtml += '</td>'
	postHtml += '</tr>'
	postHtml += '<tr class="isSignUpShow examType2" >'
		postHtml += '<td class="th_bg">报名</td>'
		postHtml += '<td class="allowEdit">'
			postHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" name="signUp" value="1" class="bidFileEdit" style="vertical-align: -2px;margin-right: 5px;" />是'
			postHtml += '</label>'
			postHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" checked="checked" name="signUp" class="bidFileEdit" value="0" style="vertical-align: -2px;margin-right: 5px;" />否'
			postHtml += '</label>'
		postHtml += '</td>'
		postHtml += '<td class="th_bg"><span class="signUpShow">报名是否需要确认</span></td>'
		postHtml += '<td class="allowEdit">'
			postHtml += '<div class="signUpShow" style="width: 260px;">'
				postHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
					postHtml += '<input type="radio" class="bidFileEdit" name="enterSignUp" value="1" style="vertical-align: -2px;margin-right: 5px;" />是'
				postHtml += '</label>'
				postHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
					postHtml += '<input type="radio" class="bidFileEdit" checked="checked" name="enterSignUp" value="0" style="vertical-align: -2px;margin-right: 5px;" />否'
				postHtml += '</label>'
			postHtml += '</div>'
		postHtml += '</td>'
	postHtml += '</tr>'
	/* 新增字段【评审费承担方*】，必填项。单选，选项1：中（选）标单位；选项2：代理机构。无默认值。    2024.6.21    代理服务费线上电子票开票方案 */
	if(feeConfirmVersion == 2){
		postHtml += '<tr class="examType2">'
			postHtml += '<td class="th_bg">评审费是否含在代理服务费中<i class="red">*</i></td>'
			postHtml += '<td colspan="3">'
				postHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
					postHtml += '<input type="radio" name="feeUnderparty" value="1" style="vertical-align: -2px;margin-right: 5px;" />含在代理服务费中（代理机构承担）'
				postHtml += '</label>'
				postHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
					postHtml += '<input type="radio" name="feeUnderparty" value="0" style="vertical-align: -2px;margin-right: 5px;" />另行结算-中标（选）单位支付'
				postHtml += '</label>'
				postHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
					postHtml += '<input type="radio" name="feeUnderparty" value="2" style="vertical-align: -2px;margin-right: 5px;" />另行结算-招标人（委托方）支付'
				postHtml += '</label>'
			postHtml += '</td>'
		postHtml += '</tr>'
	}
	postHtml += '<tr class="examType2 checkTypeOfExamType2">'
		postHtml += '<td class="th_bg">拟采用的评标办法<i class="red">*</i></td>'
		postHtml += '<td colspan="3">'
			postHtml += '<select name="checkType" class="form-control checkType" style="width:260px;display: inline-block;"></select>'
		postHtml += '</td>'
	postHtml += '</tr>'
	postHtml += '<tr class="cost zbfwf examType2">'
		postHtml += '<td class="th_bg">中标服务费收取方式<i class="red">*</i></td>'
		postHtml +='<td>'
			postHtml +='<input type="hidden" class="costName" value="中标服务费" />'
			postHtml +='<input type="hidden" class="payModel" value="2" />'
			postHtml +='<input type="hidden" class="isPay" value="1" />'
			postHtml +='<select class="form-control payType" style="width:auto;display: inline-block;">'
				postHtml +='<option value="3">标准累进制</option>'
				postHtml +='<option value="1">固定金额</option>'
				postHtml +='<option value="2">固定比例</option>'
		  postHtml += '</select>'
		postHtml +='</td>'
		postHtml +='<td class="th_bg payTypeTit">优惠系数（如8折输0.8）<i class="red">*</i></td>'
		postHtml +='<td class="payTypeMain">'
			postHtml +='<div class="zjDiscount"><input type="number" class="form-control discount" oninput="priceInput(this,6)" datatype="positiveNum" errormsg="请正确输入优惠系数" style="display: inline-block;width: 260px;" value="1" /></div>'
			postHtml += '<div class="zjPayRatio" style="display: none;"><input type="text" class="form-control payRatio examOfPost" oninput="priceInput(this,6)" errormsg="请正确输入中标服务费收费比例" style="display: inline-block;width: 260px;" /></div>'
			postHtml += '<div class="zjPayMoney" style="display: none;"><input type="text" class="form-control payMoney examOfPost" oninput="priceInput(this,2)" errormsg="请正确输入中标服务费收费金额" style="display: inline-block;width: 260px;" /></div>'
		postHtml += '</td>'
	postHtml += '</tr>'
	postHtml += '<tr class="isBidTypeShow examType2">'
		postHtml += '<td class="th_bg">是否暗标</td>'
		postHtml += '<td >'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" name="bidType" value="1" style="vertical-align: -2px;margin-right: 5px;" >是'
			postHtml += '</label>'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" name="bidType" value="0" checked="checked" style="vertical-align: -2px;margin-right: 5px;" >否'
			postHtml += '</label>'
		postHtml += '</td>'
		postHtml += '<td class="th_bg"><span>投标报价方式</span></td>'
		postHtml += '<td >'
			postHtml += '<div>'
			postHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" name="bidderPriceType"checked="checked" value="1" style="vertical-align: -2px;margin-right: 5px;" />金额（元/万元）'
			postHtml += '</label>'
			postHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				postHtml += '<input type="radio"  name="bidderPriceType" value="9" style="vertical-align: -2px;margin-right: 5px;" />费率'
			postHtml += '</label>'
			postHtml += '</div>'
		postHtml += '</td>'
	postHtml += '</tr>'
	postHtml += '<tr class="projectShow examType2">'
		postHtml += '<td class="th_bg">清单文件</td>'
		postHtml += '<td colspan="3">'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" name="isHasDetailedListFile" id="" value="1" style="vertical-align: -2px;margin-right: 5px;" />有'
			postHtml += '</label>'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" checked="checked" name="isHasDetailedListFile" id="" value="0" style="vertical-align: -2px;margin-right: 5px;" />无'
			postHtml += '</label>'
		postHtml += '</td>'
	postHtml += '</tr>'
	postHtml += '<tr class="cost examType2">'
		postHtml += '<td class="th_bg">出售招标文件</td>'
		postHtml += '<td>'
			postHtml += '<input type="hidden" class="costName" value="招标文件费" />'
			postHtml += '<input type="hidden" class="payModel" value="1" />'
			postHtml += '<label style="padding:7px 20px 7px 0;margin-bottom: 0;">'
				postHtml += '<input type="radio" class="isPay iptPay" name="zbwjf" value="1" checked="checked" style="vertical-align: -2px;margin-right: 5px;">是'
			postHtml += '</label>'
			postHtml += '<label style="padding:7px 20px 7px 0;margin-bottom: 0;">'
				postHtml += '<input type="radio" class="isPay iptPay" name="zbwjf" value="0" style="vertical-align: -2px;margin-right: 5px;">否'
			postHtml += '</label>'
		postHtml += '</td>'
		postHtml += '<td class="th_bg"><span class="costShow">招标文件标书费（<span style="color: #BB2413;">元</span>）<i class="red">*</i></span></td>'
		postHtml += '<td>'
			postHtml += '<input type="number" oninput="priceInput(this,2)" class="form-control pay_input costShow payMoney examOfPost"  value="" style="width: 260px;" errormsg="请正确输入招标文件费金额"/>'
		postHtml += '</td>'  
	postHtml += '</tr>'
	postHtml += '<tr class="projectShow examType2">'
		postHtml += '<td class="th_bg">招标控制价</td>'
		postHtml += '<td colspan="3">'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" name="isHasControlPrice" value="1" style="vertical-align: -2px;margin-right: 5px;" />有'
			postHtml += '</label>'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" checked="checked" name="isHasControlPrice" value="0" style="vertical-align: -2px;margin-right: 5px;" />无'
			postHtml += '</label>'
		postHtml += '</td>'
	   /* postHtml += '<td class="th_bg"><span class="controlShow">控制价发布</span></td>'
		postHtml += '<td>'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;" class="controlShow">'
				postHtml += '<input type="radio" name="isControlPrice" value="1" style="vertical-align: -2px;margin-right: 5px;" />是'
			postHtml += '</label>'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;" class="controlShow">'
				postHtml += '<input type="radio" checked="checked" name="isControlPrice" value="0" style="vertical-align: -2px;margin-right: 5px;" />否'
			postHtml += '</label>'
		postHtml += '</td>' */
	postHtml += '</tr>'
	postHtml += '<tr class="examType2">'
		postHtml += '<td class="th_bg">是否收取投标保证金</td>'
		postHtml += '<td colspan="3">'
		   postHtml += '<label style="padding-right: 20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" checked="checked" name="isCollectDeposit" value="1" style="vertical-align: -2px;margin-right: 5px;" />是'
			postHtml += '</label>'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" name="isCollectDeposit" value="0" style="vertical-align: -2px;margin-right: 5px;" />否'
			postHtml += '</label>'
		postHtml += '</td>'
	postHtml += '</tr>'
	postHtml += '<tr class="isCollectDeposit examType2">'
		postHtml += '<td class="th_bg">保证金计算方式</td>'
		postHtml += '<td>'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" checked="checked" name="depositType" value="1" style="vertical-align: -2px;margin-right: 5px;" />固定金额'
			postHtml += '</label>'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" name="depositType" value="2" style="vertical-align: -2px;margin-right: 5px;" />固定比例'
			postHtml += '</label>'
		postHtml += '</td>'
		postHtml += '<td class="th_bg depositTit">保证金金额（<span style="color: #BB2413;">元</span>）<i class="red">*</i></td>'
		postHtml += '<td class="depositMain">'
			postHtml += '<div class="depositMoney" style="width: 260px;"><input type="number" name="depositMoney" datatype="positiveNum" oninput="priceInput(this,2)" errormsg="请正确输入保证金金额" class="form-control examOfPost" style="width: 260px;"/></div>'
			postHtml += '<div class="depositRatio" style="display: none;width: 260px;"><input type="number" name="depositRatio" oninput="priceInput(this,2)" errormsg="请正确输入保证金比例" class="form-control examOfPost" style="width: 100px;display: inline-block;"/></div>'
		postHtml += '</td>'
	postHtml += '</tr>'
	postHtml += '<tr class="isCollectDeposit examType2">'
		postHtml += '<td class="th_bg">保证金收取人<i class="red">*</i></td>'
		postHtml += '<td>'
			postHtml += '<select name="depositCollect" class="form-control select" selectname="depositCollect" style="width: auto;display: inline-block;"></select>'
		postHtml += '</td>'
		postHtml += '<td class="th_bg">保证金递交方式</td>'
		postHtml += '<td>'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" checked="checked" name="depositChannelType" value="1" style="vertical-align: -2px;margin-right: 5px;" />线上'
			postHtml += '</label>'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;">'
				postHtml += '<input type="radio" name="depositChannelType" value="2" style="vertical-align: -2px;margin-right: 5px;" />线下'
			postHtml += '</label>'
		postHtml += '</td>'
	postHtml += '</tr>'
	postHtml += '<tr class="isCollectDeposit virtualBondRules examType2">'
		postHtml += '<td  class="th_bg">投标保证金缴纳方式<i class="red">*</i></td>'
		postHtml += '<td colspan="3" style="text-align: left;">'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;" class="type_online">'
				postHtml += '<input style="vertical-align: -2px;margin-right: 5px;margin-left: 5px;" type="checkbox" checked="checked" name="depositChannel" value="1"/>资金现金'
			postHtml += '</label>'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;" class="type_online">'
				postHtml += '<input style="vertical-align: -2px;margin-right: 5px;margin-left: 5px;" type="checkbox" name="depositChannel" value="2"/>银行保函'
			postHtml += '</label>'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;" class="type_online">'
				postHtml += '<input style="vertical-align: -2px;margin-right: 5px;margin-left: 5px;" type="checkbox" name="depositChannel" value="3"/>担保'
			postHtml += '</label>'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;" class="type_online">'
				postHtml += '<input style="vertical-align: -2px;margin-right: 5px;margin-left: 5px;" type="checkbox" name="depositChannel" value="4"/>电汇'
			postHtml += '</label>'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;" class="type_online">'
				postHtml += '<input style="vertical-align: -2px;margin-right: 5px;margin-left: 5px;" type="checkbox" name="depositChannel" value="5"/>汇票'
			postHtml += '</label>'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;" class="type_online">'
				postHtml += '<input style="vertical-align: -2px;margin-right: 5px;margin-left: 5px;" type="checkbox" name="depositChannel" value="6"/>支票'
			postHtml += '</label>'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;" class="type_offline">'
				postHtml += '<input style="vertical-align: -2px;margin-right: 5px;margin-left: 5px;" type="checkbox" name="depositChannel" value="7"/>虚拟子账户'
			postHtml += '</label>'
			postHtml += '<label style="padding-right: 20px;margin-bottom: 0;" class="type_online">'
				postHtml += '<input style="vertical-align: -2px;margin-right: 5px;margin-left: 5px;" type="checkbox" name="depositChannel" value="9"/>其他'
			postHtml += '</label>'
		postHtml += '</td>'
	postHtml += '</tr>'
	postHtml += '<tr class="projectShow cost drawCost examType2">'
		postHtml += '<td class="th_bg">图纸文件</td>'
		postHtml += '<td class="isFile">'
			postHtml += '<input type="hidden" class="costName" value="图纸文件押金费" />'
			postHtml += '<input type="hidden" class="payModel" value="1" />'
			postHtml += '<label style="padding:7px 20px 7px 0;margin-bottom: 0;">'
				postHtml += '<input type="radio" class="isPay iptPay" name="draw" value="1" style="vertical-align: -2px;margin-right: 5px;" />有'
			postHtml += '</label>'
			postHtml += '<label style="padding:7px 20px 7px 0;margin-bottom: 0;">'
				postHtml += '<input type="radio" checked="checked" class="isPay iptPay" name="draw" value="0" style="vertical-align: -2px;margin-right: 5px;" />无'
			postHtml += '</label>'
		postHtml += '</td>'
		postHtml += '<td class="th_bg"><span class="costShow">押金金额（<span style="color: #BB2413;">元</span>）<i class="red">*</i></span></td>'
		postHtml += '<td><input type="text" oninput="priceInput(this,2)" class="form-control fileMoney pay_input payMoney costShow examOfPost" errormsg="请正确输入押金金额" style="width: 260px;"/></td>'
	postHtml += '</tr>'
	postHtml += '<tr class="projectShow examType2">'
		postHtml += '<td class="th_bg">工期（日历天）</td>'
		postHtml += '<td>'
			postHtml += '<input type="number" name="projectDuration" class="form-control" ignore="ignore" oninput="priceInput(this,0)" datatype="positiveNum" errormsg="请正确输入工期" style="width: 200px;" value=""/>'
		postHtml += '</td>'
		postHtml += '<td class="th_bg">建设地点</td>'
		postHtml += '<td>'
			postHtml += '<input type="text" name="buildAddress" class="form-control"  value="" style="width: 260px;"/>'
		postHtml += '</td>'
	postHtml += '</tr>'
}
/* 预审标段部分 */
var preHtml = '';
function creatPreHtml(){
	preHtml += '<tr class="isOnline examType1">'
		preHtml += '<td class="th_bg">资格预审文件获取方式</td>'
		preHtml += '<td>'
			preHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				preHtml += '<input type="radio" checked="checked" class="bidFileEdit" name="pretrialGetFileType" value="1" style="vertical-align: -2px;margin-right: 5px;" />线上获取'
			preHtml += '</label>'
		preHtml += '</td>'
		preHtml += '<td class="th_bg">资格申请文件递交形式</td>'
		preHtml += '<td>'
			preHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				preHtml += '<input type="radio" checked="checked" class="bidFileEdit" name="pretrialDeliverFileType" id="" value="1" style="vertical-align: -2px;margin-right: 5px;" />线上递交'
			preHtml += '</label>'
			preHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				preHtml += '<input type="radio" class="bidFileEdit" name="pretrialDeliverFileType" id="" value="2" style="vertical-align: -2px;margin-right: 5px;" />线下递交'
			preHtml += '</label>'
		preHtml += '</td>'
	preHtml += '</tr>'
	preHtml += '<tr class="isOnline examType1">'
		
		preHtml += '<td class="th_bg">资格申请文件开启形式</td>'
		preHtml += '<td>'
			preHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				preHtml += '<input type="radio" checked="checked" class="bidFileEdit" name="pretrialOpenType" id="" value="1" style="vertical-align: -2px;margin-right: 5px;" />线上开启'
			preHtml += '</label>'
			preHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				preHtml += '<input type="radio" class="bidFileEdit" name="pretrialOpenType" id="" value="2" style="vertical-align: -2px;margin-right: 5px;" />线下开启'
			preHtml += '</label>'
		preHtml += '</td>'
		preHtml += '<td class="th_bg">资格审查形式</td>'
		preHtml += '<td>'
			preHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				preHtml += '<input type="radio" class="bidFileEdit" checked="checked" name="pretrialReviewType" id="" value="1" style="vertical-align: -2px;margin-right: 5px;" />线上评审'
			preHtml += '</label>'
			preHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				preHtml += '<input type="radio" class="bidFileEdit" name="pretrialReviewType" id="" value="2" style="vertical-align: -2px;margin-right: 5px;" />线下评审'
			preHtml += '</label>'
			
		preHtml += '</td>'
	preHtml += '</tr>'
	preHtml += '<tr class="isSignUpShow examType1" >'
		preHtml += '<td class="th_bg">报名</td>'
		preHtml += '<td class="allowEdit">'
			preHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				preHtml += '<input type="radio" class="bidFileEdit" name="signUp" value="1" style="vertical-align: -2px;margin-right: 5px;" />是'
			preHtml += '</label>'
			preHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
				preHtml += '<input type="radio" class="bidFileEdit" checked="checked" name="signUp" value="0" style="vertical-align: -2px;margin-right: 5px;" />否'
			preHtml += '</label>'
		preHtml += '</td>'
		preHtml += '<td class="th_bg"><span class="signUpShow">报名是否需要确认</span></td>'
		preHtml += '<td class="allowEdit">'
			preHtml += '<div class="signUpShow" style="width: 260px;">'
				preHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
					preHtml += '<input type="radio" class="bidFileEdit" name="enterSignUp" value="1" style="vertical-align: -2px;margin-right: 5px;" />是'
				preHtml += '</label>'
				preHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
					preHtml += '<input type="radio" class="bidFileEdit" checked="checked" name="enterSignUp" value="0" style="vertical-align: -2px;margin-right: 5px;" />否'
				preHtml += '</label>'
			preHtml += '</div>'
		preHtml += '</td>'
	preHtml += '</tr>'
	/* 新增字段【评审费承担方*】，必填项。单选，选项1：中（选）标单位；选项2：代理机构。无默认值。    2024.6.21    代理服务费线上电子票开票方案 */
	if(feeConfirmVersion == 2){
		preHtml += '<tr class="examType1">'
			preHtml += '<td class="th_bg">评审费是否含在代理服务费中<i class="red">*</i></td>'
			preHtml += '<td colspan="3">'
				preHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
					preHtml += '<input type="radio" name="feeUnderparty" value="1" style="vertical-align: -2px;margin-right: 5px;" />含在代理服务费中（代理机构承担）'
				preHtml += '</label>'
				preHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
					preHtml += '<input type="radio" name="feeUnderparty" value="0" style="vertical-align: -2px;margin-right: 5px;" />另行结算-中标（选）单位支付'
				preHtml += '</label>'
				preHtml += '<label style="padding-right:20px;margin-bottom: 0;">'
					preHtml += '<input type="radio" name="feeUnderparty" value="2" style="vertical-align: -2px;margin-right: 5px;" />另行结算-招标人（委托方）支付'
				preHtml += '</label>'
			preHtml += '</td>'
		preHtml += '</tr>'
	}
	preHtml += '<tr class="examType1">'
		preHtml += '<td class="th_bg">预审评审办法<i class="red">*</i></td>'
		preHtml += '<td>'
			preHtml += '<select name="pretrialCheckType" id="pretrialCheckType" class="form-control bidFileEdit" style="width:auto;display: inline-block;">'
				preHtml += '<option value="1">合格制</option>'
				preHtml += '<option value="2">有限数量制</option>'
			preHtml += '</select>'
		preHtml += '</td>'
		preHtml += '<td class="th_bg"><span class="limitNum" style="display: none;">限制人数<i class="red">*</i></span></td>'
		preHtml += '<td>'
			preHtml += '<input type="number"  name="pretrialPassNumber" id="pretrialPassNumber"  class="form-control limitNum bidFileEdit" onkeyup="priceInput(this,0)" datatype="num" errormsg="请输入限制人数" style="width: 260px;display: none;"/>'
		preHtml += '</td>'
	preHtml += '</tr>'
	preHtml += '<tr class="cost examType1">'
		preHtml += '<td class="th_bg">资格预审文件是否出售</td>'
		preHtml += '<td>'
			preHtml += '<input type="hidden" class="costName" value="资格预审文件费" />'
			preHtml += '<input type="hidden" class="payModel" value="0" />'
			preHtml += '<label style="padding:7px 20px 7px 0;margin-bottom: 0;">'
				preHtml += '<input type="radio" name="yswjf"  class="isPay iptPay bidFileEdit" value="1" checked="checked" style="vertical-align: -2px;margin-right: 5px;" data-pay="zgyswjf">是'
			preHtml += '</label>'
			preHtml += '<label style="padding:7px 20px 7px 0;margin-bottom: 0;">'
				preHtml += '<input type="radio" name="yswjf" class="isPay iptPay bidFileEdit" value="0" style="vertical-align: -2px;margin-right: 5px;" data-pay="zgyswjf">否'
			preHtml += '</label>'
		preHtml += '</td>'
		preHtml += '<td class="th_bg"><span class="costShow">资格预审文件费（<span style="color: #BB2413;">元</span>）<i class="red">*</i></span></td>'
		preHtml += '<td>'
			preHtml += '<input type="number" oninput="priceInput(this,2)" class="form-control pay_input costShow payMoney examOfPre bidFileEdit"  value="" style="width: 260px;" errormsg="请正确输入资格预审文件费金额"/>'
		preHtml += '</td>'  
	preHtml += '</tr>'
	preHtml += '<tr class="examType1">'
		preHtml += '<td class="th_bg">是否提前编制招标文件</td>'
		preHtml += '<td colspan="3" class="allowEdit">'
			preHtml += '<label style="padding:7px 20px 7px 0;margin-bottom: 0;">'
				preHtml += '<input type="radio" name="isAdvanceBidFile" value="1" checked="checked" style="vertical-align: -2px;margin-right: 5px;"  class="pay">是'
			preHtml += '</label>'
			preHtml += '<label style="padding:7px 20px 7px 0;margin-bottom: 0;">'
				preHtml += '<input type="radio" name="isAdvanceBidFile" value="0" style="vertical-align: -2px;margin-right: 5px;"  class="pay">否'
			preHtml += '</label>'
		preHtml += '</td>'
	preHtml += '</tr>'
	preHtml += '<tr class="examType1 checkTypeOfExamType">'
		preHtml += '<td class="th_bg">拟采用的评标办法<i class="red">*</i></td>'
		preHtml += '<td colspan="3">'
			preHtml += '<select name="checkType" class="form-control checkType" style="width:260px;display: inline-block;"></select>'
		preHtml += '</td>'
	preHtml += '</tr>'
	preHtml += '<tr class="projectShow examType1 preparedness">'
		preHtml += '<td class="th_bg">清单文件</td>'
		preHtml += '<td colspan="3">'
			preHtml += '<label style="padding-right: 20px;margin-bottom: 0;">'						
				preHtml += '<input type="radio" name="isHasDetailedListFile" id="" value="1" style="vertical-align: -2px;margin-right: 5px;" />有'
				
			preHtml += '</label>'
			preHtml += '<label style="padding-right: 20px;margin-bottom: 0;">'
				preHtml += '<input type="radio" checked="checked" name="isHasDetailedListFile" id="" value="0" style="vertical-align: -2px;margin-right: 5px;" />无'
			preHtml += '</label>'
		preHtml += '</td>'
	preHtml += '</tr>'
	preHtml += '<tr class="projectShow examType1 preparedness">'
		preHtml += '<td class="th_bg">招标控制价</td>'
		preHtml += '<td colspan="3">'
			preHtml += '<label style="padding-right: 20px;margin-bottom: 0;">'
				preHtml += '<input type="radio" name="isHasControlPrice" value="1" style="vertical-align: -2px;margin-right: 5px;" />有'
			preHtml += '</label>'
			preHtml += '<label style="padding-right: 20px;margin-bottom: 0;">'
				preHtml += '<input type="radio" checked="checked" name="isHasControlPrice" value="0" style="vertical-align: -2px;margin-right: 5px;" />无'
			preHtml += '</label>'
		preHtml += '</td>'
		/* preHtml += '<td class="th_bg"><span class="controlShow">控制价发布</span></td>'
		preHtml += '<td>'
			preHtml += '<label style="padding-right: 20px;margin-bottom: 0;" class="controlShow">'
				preHtml += '<input type="radio" name="isControlPrice" value="1" style="vertical-align: -2px;margin-right: 5px;" />是'
			preHtml += '</label>'
			preHtml += '<label style="padding-right: 20px;margin-bottom: 0;" class="controlShow">'
				preHtml += '<input type="radio" checked="checked" name="isControlPrice" value="0" style="vertical-align: -2px;margin-right: 5px;" />否'
			preHtml += '</label>'
		preHtml += '</td>' */
	preHtml += '</tr>'
}