function Supplement() {
	var list = ""
	if(projectSupplements.length > 0) {
		list += '<tr>'
		list += '<td class="th_bg">公告开始时间</td>'
		list += '<td colspan="3" style="text-align: left;">'
		list += '<div id="noticeStartDate"></div>'
		list += '</td>'
		list += '</tr>'
		list += '<tr>'
		list += '<td class="th_bg">公告截止时间</td>'
		list += '<td  style="text-align: left;">'
		list += '<div id="noticeEndDate"></div>'
		list += '</td>'
		list += '<td class=" th_bg" >原始公告截止时间</td>'
		list += '<td style="text-align: left;">'
		list += '<div id="oldNoticeEndDate"></div>'
		list += '</td>'
		list += '</tr>'
		list += '<tr>'
		list += '<td class="th_bg">提出澄清截止时间</td>'
		list += '<td style="text-align: left;">'
		list += '<div id="askEndDate"></div>'
		list += '</td>'
		list += '<td class="th_bg">原始答复截止时间</td>'
		list += '<td  style="text-align: left;">'
		list += '<div id="oldAskEndDate"></div>'
		list += '</td>'
		list += '</tr>'
		list += '<tr>'
		list += '<td class="th_bg">答复截止时间</td>'
		list += '<td style="text-align: left;">'
		list += '<div id="answersEndDate"></div>'
		list += '</td>'
		list += '<td class="th_bg">原始答复截止时间</td>'
		list += '<td style="text-align: left;">'
		list += '<div id="oldAnswersEndDate"></div>'
		list += '</td>'
		list += '</tr>'

		list += '<tr>'
		list += '<td class="th_bg">竞卖开始时间</td>'
		list += '<td class="" style="text-align: left;">'
		list += '<div id="auctionStartDate"></div>'
		list += '</td>'
		list += '<td class="oldTime th_bg" >原始竞卖开始时间</td>'
		list += '<td class="oldTime" style="text-align: left;">'
		list += '<div id="oldAuctionStartDate"></div>'
		list += '</td>'
		list += '</tr>'
		if((purchaseaData.project[0].groupCode != "" || purchaseaData.project[0].groupCode != null || purchaseaData.project[0].groupCode != undefined) && purchaseaData.project[0].groupCode == "00270012") {
			list += '<tr>'
			list += '<td class="th_bg">竞卖结束时间</td>'
			list += '<td class="" style="text-align: left;">'
			list += '<div id="auctionDateEnd"></div>'
			list += '</td>'
			list += '<td class="oldTime th_bg" >原始竞卖结束时间</td>'
			list += '<td class="oldTime" style="text-align: left;">'
			list += '<div id="oldAuctionDateEnd"></div>'
			list += '</td>'
			list += '</tr>'
		}
		if((purchaseaData.project[0].groupCode != "" || purchaseaData.project[0].groupCode != null || purchaseaData.project[0].groupCode != undefined) && purchaseaData.project[0].groupCode == "00270012") {
			list += '<tr>'

			list += '<td class="th_bg">是否递交竞卖文件</td>'
			list += '<td style="text-align: left;">'
			list += '<div id="isFileText"></div>'
			list += '</td>'
			list += '<td class="th_bg">是否物料关系设置</td>'
			list += '<td style="text-align: left;">'
			list += '<div id="materialRelationship"></div>'
			list += '</td>'
			list += '</tr>'
		} else {
			list += '<tr>'
			list += '<td class="th_bg">是否递交竞卖文件</td>'
			list += '<td style="text-align: left;">'
			list += '<div id="isFileText"></div>'
			list += '</td>'
			if(purchaseaData.isFile == 0) {
				if(purchaseaData.project[0].manual==1) {
					if(purchaseaData.supplierCount) {
						list += '<td class="th_bg">	最少供应商数量</td>'
						list += '<td colspan="3" style="text-align: left;">'
						list += '<div id="supplierCount"></div>'
						list += '</td>'
					}
				}
			}
			list += '</tr>'
		}
		if(purchaseaData.isFile == 0) {
			list += '<tr class="isFileDate">'
			list += '<td class="th_bg">竞卖文件递交截止时间</td>'
			list += '<td class="newTime" style="text-align: left;">'
			list += '<div id="fileEndDate" style="display: inline-block;"></div><div style="padding: 5px" class="red">（即竞卖文件审核开始时间）</div>'
			list += '</td>'
			list += '<td class="oldTime th_bg" >原始竞卖文件递交截止时间</td>'
			list += '<td class="oldTime" colspan="2" style="text-align: left;">'
			list += '<div id="oldFileEndDate"></div>	 '
			list += '</td>'
			list += '</tr>'
			list += '<tr class="isFileDate">'
			list += '<td class="th_bg">竞卖文件审核截止时间</td>'
			list += '<td class="newTime" style="text-align: left;">'
			list += '<div id="fileCheckEndDate"></div><div style="padding: 5px" class="red">（竞卖文件递交截止时间后才能开始审核，请预留足够的审核时间）</div>'
			list += '</td>'
			list += '<td class="oldTime th_bg" >原始竞卖文件审核截止时间</td>'
			list += '<td class="oldTime" colspan="2" style="text-align: left;">'
			list += '<div id="oldFileCheckEndDate"></div>'
			list += '</td>'
			list += '</tr>'
		}

	} else {
		list += '<tr>'
		list += '<td class="th_bg">公告开始时间</td>'
		list += '<td style="text-align: left;">'
		list += '<div id="noticeStartDate"></div>'
		list += '</td>'
		list += '<td class="th_bg">公告截止时间</td>'
		list += '<td  style="text-align: left;">'
		list += '<div id="noticeEndDate"></div>'
		list += '</td>'
		list += '</tr>'
		list += '<tr>'
		list += '<td class="th_bg">提出澄清截止时间</td>'
		list += '<td style="text-align: left;">'
		list += '<div id="askEndDate"></div>'
		list += '</td>'
		list += '<td class="th_bg">答复截止时间</td>'
		list += '<td style="text-align: left;">'
		list += '<div id="answersEndDate"></div>'
		list += '</td>'
		list += '</tr>'
		list += '<tr>'
		list += '<td class="th_bg">竞卖开始时间</td>'
		list += '<td style="text-align: left;">'
		list += '<div id="auctionStartDate"></div>'
		list += '</td>'
		if((purchaseaData.project[0].groupCode != "" || purchaseaData.project[0].groupCode != null || purchaseaData.project[0].groupCode != undefined) && purchaseaData.project[0].groupCode == "00270012") {
			list += '<td class="th_bg">竞卖结束时间</td>'
			list += '<td style="text-align: left;">'
			list += '<div id="auctionDateEnd"></div>'
			list += '</td>'
		} else {
			list += '<td class="th_bg"></td>'
			list += '<td style="text-align: left;">'
			list += '</td>'
		}
		list += '</tr>'
		if((purchaseaData.project[0].groupCode != "" || purchaseaData.project[0].groupCode != null || purchaseaData.project[0].groupCode != undefined) && purchaseaData.project[0].groupCode == "00270012") {
			list += '<tr>'

			list += '<td class="th_bg">是否递交竞卖文件</td>'
			list += '<td style="text-align: left;">'
			list += '<div id="isFileText"></div>'
			list += '</td>'
			list += '<td class="th_bg">是否物料关系设置</td>'
			list += '<td style="text-align: left;">'
			list += '<div id="materialRelationship"></div>'
			list += '</td>'
			list += '</tr>'
		} else {
			list += '<tr>'
			list += '<td class="th_bg">是否递交竞卖文件</td>'
			list += '<td style="text-align: left;">'
			list += '<div id="isFileText"></div>'
			list += '</td>'
			if(purchaseaData.isFile == 0) {
				if(purchaseaData.project[0].manual==1) {
					if(purchaseaData.supplierCount) {
						list += '<td class="th_bg">	最少供应商数量</td>'
						list += '<td colspan="3" style="text-align: left;">'
						list += '<div id="supplierCount"></div>'
						list += '</td>'
					}
				}
			}
			list += '</tr>'
		}
		//	     	list+='<tr>'
		//	     		list+='<td class="th_bg">是否递交竞卖文件</td>'
		//	     		list+='<td colspan="3" style="text-align: left;">'
		//	     			list+='<div id="isFileText"></div>'
		//	     		list+='</td>'
		//	     	list+='</tr>'
		if(purchaseaData.isFile == 0) {
			list += '<tr class="isFileDate">'
			list += '<td class="th_bg">竞卖文件递交截止时间</td>'
			list += '<td class="newTime" style="text-align: left;">'
			list += '<div id="fileEndDate" style="display: inline-block;"></div><div style="padding: 5px" class="red">（即竞卖文件审核开始时间）</div>'
			list += '</td>'
			list += '<td class="th_bg">竞卖文件审核截止时间</td>'
			list += '<td class="newTime" style="text-align: left;">'
			list += '<div id="fileCheckEndDate"></div><div style="padding: 5px" class="red">（竞卖文件递交截止时间后才能开始审核，请预留足够的审核时间）</div>'
			list += '</td>'
			list += '</tr>'
		}
	}
	$("#timeTbody").html(list)
}