function Supplement() {
	var list = ""
	if(projectSupplements.length > 0) {
		list += '<tr>'
		list += '<td class="th_bg">公告开始时间</td>'
		list += '<td colspan="3" style="text-align: left;">'
		list += '<div id="noticeStartDate"></div>'
		list += '</td>'
		list += '</tr>'
		list += '<tr>'
		list += '<td class="th_bg">公告截止时间</td>'
		list += '<td  style="text-align: left;">'
		list += '<div id="noticeEndDate"></div>'
		list += '</td>'
		list += '<td class=" th_bg" >原始公告截止时间</td>'
		list += '<td style="text-align: left;">'
		list += '<div id="oldNoticeEndDate"></div>'
		list += '</td>'
		list += '</tr>'
		// list += '<tr>'
		// list += '<td class="th_bg">提出澄清截止时间</td>'
		// list += '<td style="text-align: left;">'
		// list += '<div id="askEndDate"></div>'
		// list += '</td>'
		// list += '<td class="th_bg">原始答复截止时间</td>'
		// list += '<td  style="text-align: left;">'
		// list += '<div id="oldAskEndDate"></div>'
		// list += '</td>'
		// list += '</tr>'
		list += '<tr>'
		list += '<td class="th_bg">答复截止时间</td>'
		list += '<td style="text-align: left;">'
		list += '<div id="answersEndDate"></div>'
		list += '</td>'
		list += '<td class="th_bg">原始答复截止时间</td>'
		list += '<td style="text-align: left;">'
		list += '<div id="oldAnswersEndDate"></div>'
		list += '</td>'
		list += '</tr>'
		list += '<tr>'
		list += '<td class="th_bg">竞卖开始时间</td>'
		list += '<td class="" style="text-align: left;">'
		list += '<div id="auctionStartDate"></div>'
		list += '</td>'
		list += '<td class="oldTime th_bg" >原始竞卖开始时间</td>'
		list += '<td class="oldTime" style="text-align: left;">'
		list += '<div id="oldAuctionStartDate"></div>'
		list += '</td>'
		list += '</tr>'
		//竟卖时间
		if((purchaseaData.project[0].groupCode != "" || purchaseaData.project[0].groupCode != null || purchaseaData.project[0].groupCode != undefined) && purchaseaData.project[0].groupCode == "00270012") {
			list += '<tr>'
			list += '<td class="th_bg">竞卖结束时间</td>'
			list += '<td class="" style="text-align: left;">'
			list += '<div id="auctionDateEnd"></div>'
			list += '</td>'
			list += '<td class="oldTime th_bg" >原始竞卖结束时间</td>'
			list += '<td class="oldTime" style="text-align: left;">'
			list += '<div id="oldAuctionDateEnd"></div>'
			list += '</td>'
			list += '</tr>'
		}
		if((purchaseaData.project[0].groupCode != "" || purchaseaData.project[0].groupCode != null || purchaseaData.project[0].groupCode != undefined) && purchaseaData.project[0].groupCode == "00270012") {
			list += '<tr>'

			list += '<td class="th_bg">是否递交竞卖文件</td>'
			list += '<td style="text-align: left;">'
			list += '<div id="isFileText"></div>'
			list += '</td>'
			list += '<td class="th_bg">是否物料关系设置</td>'
			list += '<td style="text-align: left;">'
			list += '<div id="materialRelationship"></div>'
			list += '</td>'
			list += '</tr>'
		} else {
			list += '<tr>'
			list += '<td class="th_bg">是否递交竞卖文件</td>'
			list += '<td colspan="3" style="text-align: left;">'
			list += '<div id="isFileText"></div>'
			list += '</td>'
			list += '</tr>'
		}
		//	     	list+='<tr>'
		//	     		list+='<td class="th_bg">是否递交竞卖文件</td>'
		//	     		list+='<td colspan="3" style="text-align: left;">'
		//	     			list+='<div id="isFileText"></div>'
		//	     		list+='</td>'
		//	     	list+='</tr>'
		if(purchaseaData.isFile == 0) {
			list += '<tr class="isFileDate">'
			list += '<td class="th_bg">竞卖文件递交截止时间</td>'
			list += '<td class="newTime" style="text-align: left;">'
			list += '<div id="fileEndDate"></div>'
			list += '</td>'
			list += '<td class="oldTime th_bg" >原始竞卖文件递交截止时间</td>'
			list += '<td class="oldTime" colspan="2" style="text-align: left;">'
			list += '<div id="oldFileEndDate"></div>	 '
			list += '</td>'
			list += '</tr>'
			list += '<tr class="isFileDate">'
			list += '<td class="th_bg">竞卖文件审核截止时间</td>'
			list += '<td class="newTime" style="text-align: left;">'
			list += '<div id="fileCheckEndDate"></div>'
			list += '</td>'
			list += '<td class="oldTime th_bg" >原始竞卖文件审核截止时间</td>'
			list += '<td class="oldTime" colspan="2" style="text-align: left;">'
			list += '<div id="oldFileCheckEndDate"></div>'
			list += '</td>'
			list += '</tr>'
		}

	} else {
		list += '<tr>'
		list += '<td class="th_bg">公告开始时间</td>'
		list += '<td style="text-align: left;">'
		list += '<div id="noticeStartDate"></div>'
		list += '</td>'
		list += '<td class="th_bg">公告截止时间</td>'
		list += '<td  style="text-align: left;">'
		list += '<div id="noticeEndDate"></div>'
		list += '</td>'
		list += '</tr>'
		// list += '<tr>'
		// list += '<td class="th_bg">提出澄清截止时间</td>'
		// list += '<td style="text-align: left;">'
		// list += '<div id="askEndDate"></div>'
		// list += '</td>'
		// list += '<td class="th_bg">答复截止时间</td>'
		// list += '<td style="text-align: left;">'
		// list += '<div id="answersEndDate"></div>'
		// list += '</td>'
		// list += '</tr>'
		if((purchaseaData.project[0].groupCode != "" || purchaseaData.project[0].groupCode != null || purchaseaData.project[0].groupCode != undefined) && purchaseaData.project[0].groupCode == "00270012") {
			list += '<tr>'
			list += '<td class="th_bg">竞卖开始时间</td>'
			list += '<td style="text-align: left;">'
			list += '<div id="auctionStartDate"></div>'
			list += '</td>'

			list += '<td class="th_bg">竞卖结束时间</td>'
			list += '<td style="text-align: left;">'
			list += '<div id="auctionDateEnd"></div>'
			list += '</td>'
			list += '</tr>'
		} else {
			list += '<tr>'
			list += '<td class="th_bg">竞卖开始时间</td>'
			list += '<td colspan="3" style="text-align: left;">'
			list += '<div id="auctionStartDate"></div>'
			list += '</td>'
			list += '</tr>'
		}
		if((purchaseaData.project[0].groupCode != "" || purchaseaData.project[0].groupCode != null || purchaseaData.project[0].groupCode != undefined) && purchaseaData.project[0].groupCode == "00270012") {
			list += '<tr>'

			list += '<td class="th_bg">是否递交竞卖文件</td>'
			list += '<td style="text-align: left;">'
			list += '<div id="isFileText"></div>'
			list += '</td>'
			list += '<td class="th_bg">是否物料关系设置</td>'
			list += '<td style="text-align: left;">'
			list += '<div id="materialRelationship"></div>'
			list += '</td>'
			list += '</tr>'
		} else {
			list += '<tr>'
			list += '<td class="th_bg">是否递交竞卖文件</td>'
			list += '<td colspan="3" style="text-align: left;">'
			list += '<div id="isFileText"></div>'
			list += '</td>'
			list += '</tr>'
		}
//		list += '<tr>'
//		list += '<td class="th_bg">是否递交竞卖文件</td>'
//		list += '<td colspan="3" style="text-align: left;">'
//		list += '<div id="isFileText"></div>'
//		list += '</td>'
//		list += '</tr>'
		if(purchaseaData.isFile == 0) {
			list += '<tr class="isFileDate">'
			list += '<td class="th_bg">竞卖文件递交截止时间</td>'
			list += '<td class="newTime" style="text-align: left;">'
			list += '<div id="fileEndDate"></div>'
			list += '</td>'
			list += '<td class="th_bg">竞卖文件审核截止时间</td>'
			list += '<td class="newTime" style="text-align: left;">'
			list += '<div id="fileCheckEndDate"></div>'
			list += '</td>'
			list += '</tr>'
		}
	}
	$("#timeTbody").html(list);

}